### ISSUE TITLE
Gathering a team

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-ruby#2]
I am expecting for the moment that I will be doing the majority of the work on this project (I'm being paid to, after all!), but I would very much appreciate it if interested parties would join a team to review said work - my Ruby is *very* Rusty after all, but even without that having a team of reviewers has proven invaluable on the Python version and I'd like to carry over that workflow.

Speaking of Rust, this project is also going to involve Rust! The plan is to implement the backend of it in Rust from very early on, using [Helix](https://usehelix.com/) to expose it to Ruby, and then to eventually extract the Rust backend into something reusable that can provide a future backend for the Python version too (and ideally other languages). So people with Rust experience would also be useful as I have *some* but nothing I could in good faith call a lot.

So, who wants to join? @HypothesisWorks/hypothesis-python-contributors are of course all *very* welcome, but I'm happy to add more or less anyone who is happy to be added. :-)

(More or less: Please note that there is a [code of conduct](https://hypothesis.readthedocs.io/en/latest/community.html#code-of-conduct) and it will be enforced. If you're not comfortable with having to adhere to it, best steer clear of joining the team).

NB: I won't be interpreting reaction emojis as a request to join. You need to actually add a comment (or let me know elsewhere) if you want to.

**Comment by mulkieran** [comment]
Me! I have some Rust experience, no Ruby experience.

**Comment by alexwlchan** [comment]
👋 

I have some Rust experience, and I pretend not to have any Ruby experience.

**Comment by Zac-HD** [comment]
Sounds fun, but I'll stick to Python for now - I've never done more than dabble in Ruby.  

I'll try to learn some Rust in time for the independent backend though; I've been meaning to get started for a while now and this sounds like a great ~~excuse~~ motivator 😄

**Comment by kxepal** [comment]
I'm with @Zac-HD (:

**Comment by tom-pang** [comment]
@DRMacIver sign me up!

**Comment by DRMacIver** [comment]
I think we've got enough to get started, although more are of course always welcome.
