### ISSUE TITLE
Update rake gem

### ISSUE THREAD

**Issue by suzannehamilton** [HypothesisWorks/hypothesis-ruby#36]
hypothesis-specs.gemspec currently specifies rake version 10.0, which is pretty old and probably incompatible with most people's Ruby projects. Any objections to bumping it to 12.3?

As a aside, what's the reason for listing gems in both the gemspec and the Gemfile? I've mostly seen gem projects structured like [this](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/), i.e. with all the dependencies listed in project-name.gemspec and a simple `gemspec` line in the Gemfile. But I won't be surprised if you tell me you need to do it differently for $horrifying_reasons. 🙂

**Comment by DRMacIver** [comment]
> hypothesis-specs.gemspec currently specifies rake version 10.0, which is pretty old and probably incompatible with most people's Ruby projects. Any objections to bumping it to 12.3?

Whoops. None at all. 

What I had *meant* to do was specify a lower bound while still being compatible with any Rake people were likely to have installed, but obviously I did completely the wrong thing. Will fix momentarily...

> As a aside, what's the reason for listing gems in both the gemspec and the Gemfile? I've mostly seen gem projects structured like this, i.e. with all the dependencies listed in project-name.gemspec and a simple gemspec line in the Gemfile. But I won't be surprised if you tell me you need to do it differently for $horrifying_reasons. 🙂

Uh, honestly just that I didn't know I could do that. No horrifying reasons that I'm aware, though I do find the idea of adding development dependencies to the gem metadata a bit weird, so for now I might leave that part as is but remove the duplication. Thanks!
